# Generated by Django 4.1 on 2022-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
